/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as NoWorkspaceRouteImport } from './routes/no-workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthPlanningRouteImport } from './routes/_auth/planning'
import { Route as AuthBoardRouteImport } from './routes/_auth/board'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const NoWorkspaceRoute = NoWorkspaceRouteImport.update({
  id: '/no-workspace',
  path: '/no-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPlanningRoute = AuthPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBoardRoute = AuthBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/no-workspace': typeof NoWorkspaceRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRoute
  '/board': typeof AuthBoardRoute
  '/planning': typeof AuthPlanningRoute
  '/settings': typeof AuthSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/no-workspace': typeof NoWorkspaceRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRoute
  '/board': typeof AuthBoardRoute
  '/planning': typeof AuthPlanningRoute
  '/settings': typeof AuthSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/no-workspace': typeof NoWorkspaceRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/board': typeof AuthBoardRoute
  '/_auth/planning': typeof AuthPlanningRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/no-workspace'
    | '/reset'
    | '/signup'
    | '/admin'
    | '/board'
    | '/planning'
    | '/settings'
    | '/auth/callback'
    | '/invitations/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/no-workspace'
    | '/reset'
    | '/signup'
    | '/admin'
    | '/board'
    | '/planning'
    | '/settings'
    | '/auth/callback'
    | '/invitations/accept'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot'
    | '/login'
    | '/no-workspace'
    | '/reset'
    | '/signup'
    | '/_auth/admin'
    | '/_auth/board'
    | '/_auth/planning'
    | '/_auth/settings'
    | '/auth/callback'
    | '/invitations/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  NoWorkspaceRoute: typeof NoWorkspaceRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-workspace': {
      id: '/no-workspace'
      path: '/no-workspace'
      fullPath: '/no-workspace'
      preLoaderRoute: typeof NoWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/planning': {
      id: '/_auth/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthPlanningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/board': {
      id: '/_auth/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthBoardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthBoardRoute: typeof AuthBoardRoute
  AuthPlanningRoute: typeof AuthPlanningRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthBoardRoute: AuthBoardRoute,
  AuthPlanningRoute: AuthPlanningRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  NoWorkspaceRoute: NoWorkspaceRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
